# Generated by Django 4.2.16 on 2025-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizer", "0022_recordedresponses_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testlogs",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
